app: remix
component: http
name: remix
inputs:
  region: ap-guangzhou
  src:
    dist: ./
    hook: cp package.json ./server/package.json &&npm i &&npm run build
    exclude:
      - .env
  faas: 
    framework: express
    runtime: Nodejs12.16
    timeout: 10 # 超时时间，单位秒
    memorySize: 512 # 内存大小，单位MB
    layers:
      - name: nextdev-layer # nodejs14环境
        version: 3
  apigw:
    service: service
    name: remixbackend
    protocols:
      - http
      - https
    environment: release
    customDomains: # 自定义域名绑定
      - domain: hello.jiahuiblog.com # 待绑定的自定义的域名
        certId: t0oNSP4s
    # 自定义路径映射的路径。使用自定义映射时，可一次仅映射一个 path 到一个环境，也可映射多个 path 到多个环境。并且一旦使用自定义映射，原本的默认映射规则不再生效，只有自定义映射路径生效。
        # customMap: true
        # pathMap:
        #   - path: /
        #     environment: release
    endpoints:
      - path: /
        method: ANY
        